### ISSUE TITLE
Final portfolio website

### ISSUE THREAD

**Issue by karenhodgkinson** [karenhodgkinson/portfolio#1]
My domain: 
KarenHodgkinson.ca

Note: I didn’t actually link my portfolio website to my domain because it’s not at the level where it should be made public. I have left the ‘Coming Soon’ page up instead. 
My portfolio website is currently hosted on Netlify: 
https://youthful-lovelace-16f4dd.netlify.com 

Rubric:

| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Details** | No sweating | Some details sweat | Sweat all the details | Disgusting, dripping, sweaty details |

Details - 1 - Some details sweat

| **Personality & design** | Bland, boring, just another graphic designer | Fairly generic, visual design could be pushed more | Quality layouts and unique, personable content & design | Unique and recognizable as you, with engaging, personable content & design |

Personality & design - 1 - Fairly generic, visual design could be pushed more

| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | Real content, well written, no grammar or spelling errors |

Text content - 3 - Real content, well written, no grammar or spelling errors

| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |

Accessibility- 1.5 - Added some alt attributes, nothing else, Just the basics: alt attributes, roles

| **Pages & images** | Barely started | Missing lots of pages & images | Has most of the pages, some placeholder images | All pages exist and are well done with complete imagery |

Pages & images - 1 - Missing lots of pages & images

| **Image quality** | Only placeholder images | Some portfolio piece images | Lots of images but low quality | High quality portfolio images — and lots of them |

Image quality - 2 - Lots of images but low quality

| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | Looks great on all screen sizes |

Responsiveness - 1 - orks on some screens

| **Performance** | Mega slow… | Slow… | Could load faster | Blazing fast awesomeness |

Performance - 1 - Slow…

| **JavaScript<br>(If it exists)** | Completely broken | Semi-functional | Works okay but the non-JavaScript experience is better | Very much improves the experience |

N/A

| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics | 

Code quality - 2 - Decent indentation, just a couple validation errors, decent semantics

Total: 13.5 / possible 27 (30 including JS)

Rationale:

Details - 1 - Some details sweat
I feel that some aspects of my website have lots of details and refinement, and other aspects are broken or missing. This was absolutely a time-management issue for me. I would like to learn how to better strategize when designing and building a website so that I have a clear understanding of how long each aspect should take me, and which aspects to focus on first.

Personality & design - 1 - Fairly generic, visual design could be pushed more
I generally always struggle with the design aspect of building a website, and often feel that my websites look cheesy and dated. I feel that my website reflects this. To improve on this for the future, I have started to be more mindful of the layout & design of the websites I use in my everyday life. 

Text content - 3 - Real content, well written, no grammar or spelling errors
I used real content for my website and put thought and effort into what I wrote. However, I should have had more text content. I was more focused on trying to get all of the pages functioning properly, and didn’t end up including everything that I had hoped to include.

Accessibility- 1.5 - Added some alt attributes, nothing else, Just the basics: alt attributes, roles
I was mindful of accessibility while building my website, but this was another casualty of my poor time-management. I included some basic roles and attributes as I went along and was thoughtful with my colours so that there would be enough contrast, but there are many elements missing.

Pages & images - 1 - Missing lots of pages & images
My repository contains all of the necessary pages and images for my website, but the functionality of my website has made it so that most of the pages & images are not accessible.

Image quality - 2 - Lots of images but low quality
I included all of the images that I would be using, but ran out of time to incorporate the high quality images.

Responsiveness - 1 - works on some screens
My website has basic responsiveness because I was mindful of this as I was writing the code, but I didn’t have time to refine the elements.

Performance - 1 - Slow…
My website definitely seems slow, but it was hard to fully gauge as the website is clearly not finished.

JavaScript - N/A - I did not include any JavaScript.

Code quality - 2 - Decent indentation, just a couple validation errors, decent semantics
I am not happy with the overall quality of my code, as it is clearly not finished. However, there are areas where I was able to put enough time and thought into the code, and these areas I am happy with. I really wish I had given myself enough time to produce a higher-quality website.

Out of all of my Web Dev projects, this is the first one that is truly unfinished. I don’t feel satisfied with the result, and I am disappointed that I didn’t accomplish the website that I had envisioned. Throughout this semester, I struggled with time management. 

I also find it difficult working with Jekyll and the pattern library. When everything goes right, I love the possibilities that patterns create. However, I generally struggle with visualizing what code will look like in the browser, and this doesn’t bode well for me when an issue could lie in the code itself, in an expression used within the pattern library, or even something silly like terminal not being restarted. I really enjoy web development, but I have a great deal of room for improvement, and I need to practice more and explore more. I think that I would benefit from allocating a limited time period to each portion of the web design and creation process, and really stick to this schedule. I tend to spend hours trying to solve one specific issue, only to realize that the problem was related to some other element. I am disappointed with my overall results, both in my pattern library and in my web site, as I understand and have learned more this semester than my work shows.

@thomasjbradley

**Comment by LKian** [comment]
Hi - I'm like to contribute.  
The page says:
"This repo doesn't have any good first issues, yet
Once its maintainers label issues and pull requests for new contributors, they will begin to appear here.
In the meantime, you can look at all of the issues in this repository."

I have a couple of suggestions and would love to contribute.  Let me know if you can get the above working.
